# Generated by Django 3.2.9 on 2021-11-25 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospmanagement', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bookvac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('patient_email', models.EmailField(max_length=100)),
                ('patient_phone', models.CharField(max_length=10)),
                ('vaccinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospmanagement.vaccinations')),
            ],
        ),
    ]
